export { default as About } from "./About/About"
export { default as Contact } from "./Contact/Contact"
export { default as Hero } from "./Hero/Hero"
export { default as Skills } from "./Skills/Skills"
export { default as Testimonial } from "./Testimonial/Testimonial"
export { default as Work } from "./Work/Work"
